### ISSUE TITLE
Support for Gen4

### ISSUE THREAD

**Issue by LuisPalacios** [wills106/homsassistant-solax-modbus#19]
Hi @wills106,

Fantastic work, just discovered and implementing it. I have a Gen3, however a friend of mine just installed a Gen4 and haven't seen it as an option while setting up the integration.

Do you have plans to integrate it?.

Thanks
Luis

**Comment by motclem** [comment]
> Hi @wills106,
> 
> Fantastic work, just discovered and implementing it. I have a Gen3, however a friend of mine just installed a Gen4 and haven't seen it as an option while setting up the integration.
> 
> Do you have plans to integrate it?.
> 
> Thanks Luis

@LuisPalacios  how do you know what generation you have?

**Comment by maxrev17** [comment]
@motclem yes, good question - I'm unsure what gen I have...

Just to add here that as a professional dev, I absolutely LOVE projects like this that I can use with such ease - thanks so much to the contributors!

**Comment by LuisPalacios** [comment]
> > Hi @wills106,
> > Fantastic work, just discovered and implementing it. I have a Gen3, however a friend of mine just installed a Gen4 and haven't seen it as an option while setting up the integration.
> > Do you have plans to integrate it?.
> > Thanks Luis
> 
> @LuisPalacios how do you know what generation you have?

HI @motclem, I bought my X1-HYBRID-G3 almost 2 years ago. My friend was offered a X1-HYBRID-G4 during the sales process. More clear answer, it's under 

solaxcloud.com > Inverter > Inverter Type > **X1-Hybrid-G3** 

Thanks, 
Luis

**Comment by motclem** [comment]
> @motclem yes, good question - I'm unsure what gen I have...
> 
> Just to add here that as a professional dev, I absolutely LOVE projects like this that I can use with such ease - thanks so much to the contributors!



> > > Hi @wills106,
> > > Fantastic work, just discovered and implementing it. I have a Gen3, however a friend of mine just installed a Gen4 and haven't seen it as an option while setting up the integration.
> > > Do you have plans to integrate it?.
> > > Thanks Luis
> > 
> > 
> > @LuisPalacios how do you know what generation you have?
> 
> HI @motclem, I bought my X1-HYBRID-G3 almost 2 years ago, by then I was offered a G3. My friend bought it 3 weeks ago and was offered a X1-HYBRID-G4 during the sales process.
> 
> You can also find you Generation under:
> 
> solaxcloud.com > Inverter > Inverter Type > (in my case says: **X1-Hybrid-G3**)
> 
> Thanks, Luis spot on mine is g3 also

tom

**Comment by motclem** [comment]
> > > Hi @wills106,
> > > Fantastic work, just discovered and implementing it. I have a Gen3, however a friend of mine just installed a Gen4 and haven't seen it as an option while setting up the integration.
> > > Do you have plans to integrate it?.
> > > Thanks Luis
> > 
> > 
> > @LuisPalacios how do you know what generation you have?
> 
> HI @motclem, I bought my X1-HYBRID-G3 almost 2 years ago, by then I was offered a G3. My friend bought it 3 weeks ago and was offered a X1-HYBRID-G4 during the sales process.
> 
> You can also find you Generation under:
> 
> solaxcloud.com > Inverter > Inverter Type > (in my case says: **X1-Hybrid-G3**)

> 
> Thanks, Luis

thanks Luis g3 for me too  when trying to install and cvonfigure the integration I get 👍 
<img width="449" alt="Screenshot 2022-02-12 at 21 19 00" src="https://user-images.githubusercontent.com/83984333/153728900-d9220288-eb9c-4019-a8ad-13dabad45bd3.png">
<img width="176" alt="Screenshot 2022-01-07 at 22 35 29" src="https://user-images.githubusercontent.com/83984333/153728906-9e75fd0d-259b-4c09-81a9-5f95f5735dee.png">

**Comment by LuisPalacios** [comment]
I documented it for myself today (sorry only in Spanish), but you'll get the idea with the screenshots... of the how to install it...

![image](https://user-images.githubusercontent.com/3615849/153730744-de36e62d-7a57-41c9-b8ec-2c3f872f67bd.png)

![image](https://user-images.githubusercontent.com/3615849/153730751-1242539b-460b-4623-be52-a74238445a14.png)

![image](https://user-images.githubusercontent.com/3615849/153730756-90afc344-f52f-4645-8421-ff9d0e3819d2.png)

Hope it helps

Luis

**Comment by LuisPalacios** [comment]
From README of this repository...

---

Installation

Copy the folder and contents of solax_modbus into to your home-assistant config/custom_components folder. After reboot of Home-Assistant, this integration can be configured through the integration setup UI

---

**Comment by LuisPalacios** [comment]
Hi,

I've finished documenting in my blog.

[https://www.luispa.com/dom%C3%B3tica/2022/02/13/hass-solax.html](https://www.luispa.com/dom%C3%B3tica/2022/02/13/hass-solax.html)

Notice it's in Spanish, please use Chrome and use the Translate to option. I tried English and works pretty well.

Hope it helps

Luis

**Comment by motclem** [comment]
> Hi,
> 
> I've finished documenting how I setup this Integration (modbus/tcp) in my blog.
> 
> https://www.luispa.com/dom%C3%B3tica/2022/02/13/hass-solax.html
> 
> Notice it's in Spanish, please use Chrome and use the Translate to option. I tried English and works pretty well.
> 
> Hope it helps
> 
> Luis

@LuisPalacios  amazing Thankyou so much got it all working now :) just meed to add in my electricity company to se battery charging times. @wills106  amazing work brilliant 👍

**Comment by wills106** [comment]
Gen 4 support is now available.

It has only been tested on an X3 so report anything wrong with X1 and I'll try and correct it.
