### ISSUE TITLE
Battery unknown 

### ISSUE THREAD

**Issue by lowprize** [wills106/homsassistant-solax-modbus#20]
I have Solax Inverter **X3-Hybiyd/Fit**
Unknown values for
  - number.solax_battery_charge
  - number.solax_battery_discharge
  - number.solax_battery_minimum_capacity
![solaxx3](https://user-images.githubusercontent.com/17613941/153572602-9913f140-61d1-4b2a-b096-fc55cf703ed9.png)

**Comment by wills106** [comment]
There was a mismatch in naming causing them not to report the state on Start / Restart of HA.

This is now fixed in 0.4.1
