### ISSUE TITLE
You need to manually add select and number entities to your Lovelace card

### ISSUE THREAD

**Issue by wills106** [wills106/homsassistant-solax-modbus#28]
You need to manually add select and number entities to your Lovelace card.
They are enabled by default but don't appear in the integration page.

Gen2 & 3

select.solax_charger_use_mode
select.solax_allow_grid_charge
number.solax_battery_charge_max_current
number.solax_battery_discharge_max_current
number.solax_battery_minimum_capacity
Gen3 Only

number.solax_forcetime_period_1_max_capacity
number.solax_forcetime_period_2_max_capacity

Gen4 ?

**Comment by matthewjporter** [comment]
On the Gen2, The only one for me I have to add manually after creating my card based on entities is:
number.solax_battery_minimum_capacity even though I select it in my list of entities. Adding after the fact is fine

Other oddertiy I have is that number.x1master_battery_charge_max_current & number.x1master_battery_discharge_max_current show as a "number" input and not a slider

![image](https://user-images.githubusercontent.com/15786074/154930500-45719c8c-e90e-442e-bdab-06a93a342231.png)

Yet number.x1master_battery_minimum_capacity gets automatically added as a slider

![image](https://user-images.githubusercontent.com/15786074/154930579-a8d27816-089c-4e45-86ae-2c1d2fec79e1.png)

Trying to find a way to override this in lovelace

**Comment by wills106** [comment]
Closing down due to being on the Todo List #37 for further investigation.
