### ISSUE TITLE
Some energy sensors without data return 

### ISSUE THREAD

**Issue by xavi104** [wills106/homsassistant-solax-modbus#3]
Hi wills106,

great work with the integration!!!

I have changed my old config for it and it is working very well. Only I have discovered two sensor that don’t show the correct value in my case: ‘SolaX Battery Input Energy Today’ and ‘SolaX Today’s Solar Energy’. They show 0 kWh everytime. Is it possible because they are not pointing to the right address? or it could be because I may have an old firmware version?

thanks in advance for your support.

**Comment by AviadorLP** [comment]
Hi wills106 first of all thanks for the integration and all your packages learn't a lot from them.
I now understand a little about python thanks to your coding and spent a real lot of hours making also a daikin energy reader from the daikin a/c's wifi modules and now i can have energy readings of all my ac's in ha. So really thanks !!!!
Still dont understand how to make an integrassion though. Too evolved for me. But packages i can make now!
Anyway just to tell you i have also a SolaX Gen 3 with battery and eps. and i have some strange results on some sensors also. Like the Solax House Load during the night always at 0.

**Comment by AviadorLP** [comment]
Also the Consumed Energy Total always at 0.
And there is a difference in values from your sensor.solax_total_solar_energy that shows in my house as 314.5 kWh and when i connect direct do the inverter i read the value 308.3 kWh, should it not be exactly the same ? How can it be more ?

**Comment by emanuelsilvapt** [comment]
Just noticed this; did you find out how to solve it?

> Also the Consumed Energy Total always at 0. And there is a difference in values from your sensor.solax_total_solar_energy that shows in my house as 314.5 kWh and when i connect directly to the inverter i read the value 308.3 kWh, should it not be exactly the same ? How can it be more ?

**Comment by AviadorLP** [comment]
No, still waiting for wills106.
If this was a package i probably could change the code but i do not understand the coding behind the integrations yet, too confusing for me and since the group read version it became more difficult for me to understand!!!

**Comment by emanuelsilvapt** [comment]
I was trying to figure out a possible "issue" but...

The only thing I found was on const.py file, line 290 "entity_registry_enabled_default=False"

But already chenged it to True with no effect...

Thanks

**Comment by AviadorLP** [comment]
Do you have the  Solax House Load during the night always at 0 ?
Probably after de inverter goes to idle ???

**Comment by emanuelsilvapt** [comment]
Yes, but I made a new sensor with:

value_template: "{{ states('sensor.solax_grid_import') | int - states('sensor.solax_grid_export') | int }}"

**Comment by AviadorLP** [comment]
Yes that should work. I really don't use the solaX sensors for this i have a shelly EM with 2 channels first gets grid import and export and second checks house load. But i use the solaX sensors to crosscheck with shelly for discrepancies, to see if they are about the same :) Thanks.
I did not know about wills106 integration at the time, otherwise i would not have bought the shelly EM, and saved some money. :( But i love the shelly plugs and most of the shelly product they are really awesome.

**Comment by emanuelsilvapt** [comment]
Yes, me too, i've 3 shelly EM's too but I think the Eastron meter is a lot more precise... I installed it in may I think, and everything ws working nicely; now I saw this inegration too and I thought it could be great to use with "Force Time Use" and installed it...
Now (literaly) I am changing utility meters to shelly until Will can check our messages... I bought him a coffee in the meanwhile...

**Comment by wills106** [comment]
House Load showing zero when charging from the grid has been fixed in 0.3.4
It should also fix House Load being zero when you batteries are flat.

sensor.solax_total_solar_energy

On my system it's the other way round, the inverter / the cloud shows more than when I connect to the Inverter via Modbus.

I think I have sort of answered on HA forum about consumed_energy_total , a number of sensors don't fully make sense and that's why I have them disabled as default.

I need to relook at some of them to see if I can get them to produce figures that make sense.

**Comment by AviadorLP** [comment]
Thank you wills106 House Load now working well for me.

**Comment by AviadorLP** [comment]
Just noticed that the solax inverter temperature also always shows 0 ºC when the inverter is idle,
don't know if this the normal behavior though ????

**Comment by wills106** [comment]
I would say it's inherited behaviour from normal non hybrid inverters.

On a non Hybrid inverter they are powered from the PV. So when the PV Voltages drop below X the inverters shut down as they are only powered by PV and don't pull from the grid.
So I would say the Hybrids are mimicking that behaviour partly shutting down, as it doesn't make sense to pull power from the grid for unneeded functionality.

**Comment by emanuelsilvapt** [comment]
Hi
Does your inverter takes "a lot" of time to adjust battery charging amps limit when you define it via integration?
From what I saw, not only it take a lot of time, but it doesnt adjust it at all if in idle; can you confirm?
Thanks a lot

**Comment by AviadorLP** [comment]
Hi Wills106 i just noticed this and went to check in the solax cloud and also on the inverter panel and i noticed the sensor.solax_export_control_factory_limit is 10 times lower then the real value.
Mine is set to 6000w and the sensor shows 600.0w

**Comment by wills106** [comment]
> Mine is set to 6000w and the sensor shows 600.0w

A Gen2 X3 is doing the same thing, need to understand what's different about your model Inverter to other Gen3 X1's

It's pretty much a static value, they only reason you would change the export limit is if you Electric distribution company put restrictions on what you can export. Or you could only supply a 16Amp feed to / from your Inverter.

**Comment by AviadorLP** [comment]
Ok so mine is one of the rare Gen 3 X1 with this bug. I can live with this. :) don't really use or need that sensor in HASS. Thanks

**Comment by wills106** [comment]
Closing down due to no response from original poster.
If there are still issues only with sensors enabled by default please open a new issue.
