### ISSUE TITLE
Solaredge Immersion Heater as a Sitch

### ISSUE THREAD

**Issue by balajibalasa** [wills106/homsassistant-solax-modbus#34]
Hi, I have an immersion controller V1 paired to the SolarEdge HD wave inverter , can you update this code to make that one available as a Switch , which can be used for automation purposes.

**Comment by wills106** [comment]
Are you posting this request on the correct repository?
If you are using an SolarEdge Immersion Heater Controller and an SolarEdge Inverter don't you need one of the SolarEdge repositories?

**Comment by wills106** [comment]
Closing down due to no response from original poster and Issue seems to be related to a different integration?
If this is related to SolaX please open a new issue with more details.

**Comment by balajibalasa** [comment]
Apologies for my mistake here , I have now posted this on the other integration , was an oversight.
