### ISSUE TITLE
sensor.solax_consumed_energy_total - Returning 0,0kwh

### ISSUE THREAD

**Issue by emanuelsilvapt** [wills106/homsassistant-solax-modbus#6]
Hi Will
Any idea why sensor.solax_consumed_energy_total is returning zero?
Solax Gen3 Hybrid
Every other sensores are working fine from what I checked already; I came from the old config and it was working fine.
Thanks a lot

**Comment by wills106** [comment]
Closing down due to being related to a disabled by default sensor.
Disabled by default sensors are on the Todo List #37 for further investigation.
